export interface Character {
  name: string;
  Aliases?: string;
  Species?: string;
  Gender?: string;
  Age?: string;
  "Hair Color"?: string;
  Status?: string;
  Residence?: string;
  Friends: string[];
  Enemies: string[];
  Occupation?: string;
  Likes?: string;
  Dislikes?: string;
  "First Appearance"?: string;
  Complexion?: string;
  Titles?: string;
  "Latest Appearance"?: string;
  "Eye Color"?: string;
  Relatives?: string;
  Ethnicity?: string;
  Location?: string;
  Leader?: string;
  Race?: string;
  Traits?: string;
  Outfit?: string;
  "Friend(s)"?: string;
  Accessories?: string;
  Allies?: string;
  Alias?: string;
  Hair?: string;
  "Relatives(s)"?: string;
  Goal?: string;
  "Voiced By"?: string;
  Sex?: string;
  "Known members"?: string;
  Name?: string;
  Birthday?: string;
}
