// Generated by https://quicktype.io

export interface Character {
  id: string;
  name: string;
  img: string;
  aliases?: string;
  species?: string;
  gender?: Gender;
  age?: string;
  hair_color?: string;
  status?: Status;
  residence?: string;
  friends: string[];
  enemies: string[];
  occupation?: string;
  likes?: string;
  dislikes?: string;
  first_appearance?: string;
  complexion?: string;
  titles?: string;
  latest_appearance?: string;
  eye_color?: string;
  relatives?: string;
  ethnicity?: string;
  location?: string;
  leader?: string;
  race?: string;
  traits?: string;
  outfit?: string;
  "friend(s)"?: string;
  accessories?: string;
  allies?: string;
  alias?: string;
  hair?: string;
  "relatives(s)"?: string;
  goal?: string;
  voiced_by?: string;
  sex?: string;
  known_members?: string;
  birthday?: string;
}

export enum Gender {
  Female = "Female ♀",
  GenderFemale = "Female",
  GenderMale = "Male",
  GenderlessØ = "Genderless ø",
  Male = "Male ♂",
  Unknown = "Unknown ?",
}

export enum Status {
  ActiveRepaired = "Active (repaired)",
  Alive = "Alive",
  Deceased = "Deceased",
  UnknownPossiblyDeceased = "Unknown (possibly deceased)",
}
